// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * Next tag: 4
 */
public final class ManualMeterEntry extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ENTERED_BLOOD_GLUCOSE_MGDL = 0;
  public static final Integer DEFAULT_METER_TIME = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer entered_blood_glucose_mgdl;

  /**
   * TODO(trhodeos): do we need this?
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer meter_time;

  @ProtoField(tag = 3)
  public final G4Timestamp timestamp;

  public ManualMeterEntry(Integer entered_blood_glucose_mgdl, Integer meter_time, G4Timestamp timestamp) {
    this.entered_blood_glucose_mgdl = entered_blood_glucose_mgdl;
    this.meter_time = meter_time;
    this.timestamp = timestamp;
  }

  private ManualMeterEntry(Builder builder) {
    this(builder.entered_blood_glucose_mgdl, builder.meter_time, builder.timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ManualMeterEntry)) return false;
    ManualMeterEntry o = (ManualMeterEntry) other;
    return equals(entered_blood_glucose_mgdl, o.entered_blood_glucose_mgdl)
        && equals(meter_time, o.meter_time)
        && equals(timestamp, o.timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = entered_blood_glucose_mgdl != null ? entered_blood_glucose_mgdl.hashCode() : 0;
      result = result * 37 + (meter_time != null ? meter_time.hashCode() : 0);
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ManualMeterEntry> {

    public Integer entered_blood_glucose_mgdl;
    public Integer meter_time;
    public G4Timestamp timestamp;

    public Builder() {
    }

    public Builder(ManualMeterEntry message) {
      super(message);
      if (message == null) return;
      this.entered_blood_glucose_mgdl = message.entered_blood_glucose_mgdl;
      this.meter_time = message.meter_time;
      this.timestamp = message.timestamp;
    }

    public Builder entered_blood_glucose_mgdl(Integer entered_blood_glucose_mgdl) {
      this.entered_blood_glucose_mgdl = entered_blood_glucose_mgdl;
      return this;
    }

    /**
     * TODO(trhodeos): do we need this?
     */
    public Builder meter_time(Integer meter_time) {
      this.meter_time = meter_time;
      return this;
    }

    public Builder timestamp(G4Timestamp timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @Override
    public ManualMeterEntry build() {
      checkRequiredFields();
      return new ManualMeterEntry(this);
    }
  }
}
