// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
import com.squareup.wire.ProtoEnum;

public enum ReceiverStatus
    implements ProtoEnum {
  /**
   * The receiver is connected to the uploader
   */
  RECEIVER_CONNECTED(0),
  /**
   * The receiver is not connected to the uploader
   */
  RECEIVER_DISCONNECTED(1);

  private final int value;

  ReceiverStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
