// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/klee/Projects/Nightscout/android-uploader/core/src/main/java/com/nightscout/core/protobuf/G4Download.proto
package com.nightscout.core.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class CookieMonsterG4Meter extends Message {

    public static final Integer DEFAULT_METER_BG_MGDL = 0;
    public static final Integer DEFAULT_METER_TIME = 0;
    public static final Long DEFAULT_TIMESTAMP_SEC = 0L;

    @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
    public final Integer meter_bg_mgdl;

    @ProtoField(tag = 2, type = UINT32)
    public final Integer meter_time;

    @ProtoField(tag = 3, type = UINT64)
    public final Long timestamp_sec;

    public CookieMonsterG4Meter(Integer meter_bg_mgdl, Integer meter_time, Long timestamp_sec) {
        this.meter_bg_mgdl = meter_bg_mgdl;
        this.meter_time = meter_time;
        this.timestamp_sec = timestamp_sec;
    }

    private CookieMonsterG4Meter(Builder builder) {
        this(builder.meter_bg_mgdl, builder.meter_time, builder.timestamp_sec);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof CookieMonsterG4Meter)) return false;
        CookieMonsterG4Meter o = (CookieMonsterG4Meter) other;
        return equals(meter_bg_mgdl, o.meter_bg_mgdl)
                && equals(meter_time, o.meter_time)
                && equals(timestamp_sec, o.timestamp_sec);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = meter_bg_mgdl != null ? meter_bg_mgdl.hashCode() : 0;
            result = result * 37 + (meter_time != null ? meter_time.hashCode() : 0);
            result = result * 37 + (timestamp_sec != null ? timestamp_sec.hashCode() : 0);
            hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<CookieMonsterG4Meter> {

        public Integer meter_bg_mgdl;
        public Integer meter_time;
        public Long timestamp_sec;

        public Builder() {
        }

        public Builder(CookieMonsterG4Meter message) {
            super(message);
            if (message == null) return;
            this.meter_bg_mgdl = message.meter_bg_mgdl;
            this.meter_time = message.meter_time;
            this.timestamp_sec = message.timestamp_sec;
        }

        public Builder meter_bg_mgdl(Integer meter_bg_mgdl) {
            this.meter_bg_mgdl = meter_bg_mgdl;
            return this;
        }

        public Builder meter_time(Integer meter_time) {
            this.meter_time = meter_time;
            return this;
        }

        public Builder timestamp_sec(Long timestamp_sec) {
            this.timestamp_sec = timestamp_sec;
            return this;
        }

        @Override
        public CookieMonsterG4Meter build() {
            checkRequiredFields();
            return new CookieMonsterG4Meter(this);
        }
    }
}
