// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/klee/Projects/Nightscout/android-uploader/core/src/main/java/com/nightscout/core/protobuf/G4Download.proto
package com.nightscout.core.protobuf;

import com.squareup.wire.ProtoEnum;

public enum Noise
        implements ProtoEnum {
    NOISE_NONE(0),
    CLEAN(1),
    LIGHT(2),
    MEDIUM(3),
    HEAVY(4),
    NOT_COMPUTED(5),
    MAX(6);

    private final int value;

    private Noise(int value) {
        this.value = value;
    }

    @Override
    public int getValue() {
        return value;
    }
}
