// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/klee/Projects/Nightscout/android-uploader/core/src/main/java/com/nightscout/core/model/Download.proto
package com.nightscout.core.model;

import com.squareup.wire.ProtoEnum;

public enum G4Insertion
        implements ProtoEnum {
  INSERTION_NONE(0),
  REMOVED(1),
  EXPIRED(2),
  RESIDUAL_DEVIATION(3),
  COUNTS_DEVIATION(4),
  SECOND_SESSION(5),
  OFF_TIME_LOSS(6),
  STARTED(7),
  BAD_TRANSMITTER(8),
  MANUFACTURING_MODE(9),
  MAX_VALUE(10);

  private final int value;

  private G4Insertion(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
