// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/klee/Projects/Nightscout/android-uploader/core/src/main/java/com/nightscout/core/model/Download.proto
package com.nightscout.core.model;

import com.squareup.wire.ProtoEnum;

public enum ReceiverStatus
        implements ProtoEnum {
    RECEIVER_CONNECTED(0),
    /**
     * The receiver is connected to the uploader
     */
    RECEIVER_DISCONNECTED(1);

    private final int value;

    private ReceiverStatus(int value) {
        this.value = value;
    }

    @Override
    public int getValue() {
        return value;
    }
}
