// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * Next tag: 14
 */
public final class G4Data extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<SensorGlucoseValue> DEFAULT_SENSOR_GLUCOSE_VALUES = Collections.emptyList();
  public static final GlucoseUnit DEFAULT_UNITS = GlucoseUnit.MGDL;
  public static final Long DEFAULT_RECEIVER_SYSTEM_TIME_SEC = 0L;
  public static final List<ManualMeterEntry> DEFAULT_MANUAL_METER_ENTRIES = Collections.emptyList();
  public static final List<RawSensorReading> DEFAULT_RAW_SENSOR_READINGS = Collections.emptyList();
  public static final List<Calibration> DEFAULT_CALIBRATIONS = Collections.emptyList();
  public static final List<Insertion> DEFAULT_INSERTIONS = Collections.emptyList();

  /**
   * Glucose records as reported by the G4
   */
  @ProtoField(tag = 1, label = REPEATED, messageType = SensorGlucoseValue.class)
  public final List<SensorGlucoseValue> sensor_glucose_values;

  /**
   * Units reported by the g4, set in the user preferences.
   */
  @ProtoField(tag = 2, type = ENUM)
  public final GlucoseUnit units;

  /**
   * Raw value of the receiver's system time. This is read directly from the receiver.
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long receiver_system_time_sec;

  @ProtoField(tag = 4)
  public final G4Metadata metadata;

  @ProtoField(tag = 5, label = REPEATED, messageType = ManualMeterEntry.class)
  public final List<ManualMeterEntry> manual_meter_entries;

  @ProtoField(tag = 6, label = REPEATED, messageType = RawSensorReading.class)
  public final List<RawSensorReading> raw_sensor_readings;

  @ProtoField(tag = 7, label = REPEATED, messageType = Calibration.class)
  public final List<Calibration> calibrations;

  @ProtoField(tag = 8, label = REPEATED, messageType = Insertion.class)
  public final List<Insertion> insertions;

  public G4Data(List<SensorGlucoseValue> sensor_glucose_values, GlucoseUnit units, Long receiver_system_time_sec, G4Metadata metadata, List<ManualMeterEntry> manual_meter_entries, List<RawSensorReading> raw_sensor_readings, List<Calibration> calibrations, List<Insertion> insertions) {
    this.sensor_glucose_values = immutableCopyOf(sensor_glucose_values);
    this.units = units;
    this.receiver_system_time_sec = receiver_system_time_sec;
    this.metadata = metadata;
    this.manual_meter_entries = immutableCopyOf(manual_meter_entries);
    this.raw_sensor_readings = immutableCopyOf(raw_sensor_readings);
    this.calibrations = immutableCopyOf(calibrations);
    this.insertions = immutableCopyOf(insertions);
  }

  private G4Data(Builder builder) {
    this(builder.sensor_glucose_values, builder.units, builder.receiver_system_time_sec, builder.metadata, builder.manual_meter_entries, builder.raw_sensor_readings, builder.calibrations, builder.insertions);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof G4Data)) return false;
    G4Data o = (G4Data) other;
    return equals(sensor_glucose_values, o.sensor_glucose_values)
        && equals(units, o.units)
        && equals(receiver_system_time_sec, o.receiver_system_time_sec)
        && equals(metadata, o.metadata)
        && equals(manual_meter_entries, o.manual_meter_entries)
        && equals(raw_sensor_readings, o.raw_sensor_readings)
        && equals(calibrations, o.calibrations)
        && equals(insertions, o.insertions);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sensor_glucose_values != null ? sensor_glucose_values.hashCode() : 1;
      result = result * 37 + (units != null ? units.hashCode() : 0);
      result = result * 37 + (receiver_system_time_sec != null ? receiver_system_time_sec.hashCode() : 0);
      result = result * 37 + (metadata != null ? metadata.hashCode() : 0);
      result = result * 37 + (manual_meter_entries != null ? manual_meter_entries.hashCode() : 1);
      result = result * 37 + (raw_sensor_readings != null ? raw_sensor_readings.hashCode() : 1);
      result = result * 37 + (calibrations != null ? calibrations.hashCode() : 1);
      result = result * 37 + (insertions != null ? insertions.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<G4Data> {

    public List<SensorGlucoseValue> sensor_glucose_values;
    public GlucoseUnit units;
    public Long receiver_system_time_sec;
    public G4Metadata metadata;
    public List<ManualMeterEntry> manual_meter_entries;
    public List<RawSensorReading> raw_sensor_readings;
    public List<Calibration> calibrations;
    public List<Insertion> insertions;

    public Builder() {
    }

    public Builder(G4Data message) {
      super(message);
      if (message == null) return;
      this.sensor_glucose_values = copyOf(message.sensor_glucose_values);
      this.units = message.units;
      this.receiver_system_time_sec = message.receiver_system_time_sec;
      this.metadata = message.metadata;
      this.manual_meter_entries = copyOf(message.manual_meter_entries);
      this.raw_sensor_readings = copyOf(message.raw_sensor_readings);
      this.calibrations = copyOf(message.calibrations);
      this.insertions = copyOf(message.insertions);
    }

    /**
     * Glucose records as reported by the G4
     */
    public Builder sensor_glucose_values(List<SensorGlucoseValue> sensor_glucose_values) {
      this.sensor_glucose_values = checkForNulls(sensor_glucose_values);
      return this;
    }

    /**
     * Units reported by the g4, set in the user preferences.
     */
    public Builder units(GlucoseUnit units) {
      this.units = units;
      return this;
    }

    /**
     * Raw value of the receiver's system time. This is read directly from the receiver.
     */
    public Builder receiver_system_time_sec(Long receiver_system_time_sec) {
      this.receiver_system_time_sec = receiver_system_time_sec;
      return this;
    }

    public Builder metadata(G4Metadata metadata) {
      this.metadata = metadata;
      return this;
    }

    public Builder manual_meter_entries(List<ManualMeterEntry> manual_meter_entries) {
      this.manual_meter_entries = checkForNulls(manual_meter_entries);
      return this;
    }

    public Builder raw_sensor_readings(List<RawSensorReading> raw_sensor_readings) {
      this.raw_sensor_readings = checkForNulls(raw_sensor_readings);
      return this;
    }

    public Builder calibrations(List<Calibration> calibrations) {
      this.calibrations = checkForNulls(calibrations);
      return this;
    }

    public Builder insertions(List<Insertion> insertions) {
      this.insertions = checkForNulls(insertions);
      return this;
    }

    @Override
    public G4Data build() {
      return new G4Data(this);
    }
  }
}
