// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * Next tag: 4
 */
public final class G4Metadata extends Message {
  private static final long serialVersionUID = 0L;

  public static final Float DEFAULT_RECEIVER_BATTERY_PERCENT = 0F;
  public static final String DEFAULT_RECEIVER_ID = "";
  public static final String DEFAULT_TRANSMITTER_ID = "";

  @ProtoField(tag = 1, type = FLOAT)
  public final Float receiver_battery_percent;

  /**
   * The receiver id reported by the dexcom g4. This uniquely identifies the device where this Data object came from.
   */
  @ProtoField(tag = 2, type = STRING)
  public final String receiver_id;

  /**
   * The transmitter id reported as used by the dexcom g4. Should look like '6A14AC'.
   */
  @ProtoField(tag = 3, type = STRING)
  public final String transmitter_id;

  public G4Metadata(Float receiver_battery_percent, String receiver_id, String transmitter_id) {
    this.receiver_battery_percent = receiver_battery_percent;
    this.receiver_id = receiver_id;
    this.transmitter_id = transmitter_id;
  }

  private G4Metadata(Builder builder) {
    this(builder.receiver_battery_percent, builder.receiver_id, builder.transmitter_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof G4Metadata)) return false;
    G4Metadata o = (G4Metadata) other;
    return equals(receiver_battery_percent, o.receiver_battery_percent)
        && equals(receiver_id, o.receiver_id)
        && equals(transmitter_id, o.transmitter_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = receiver_battery_percent != null ? receiver_battery_percent.hashCode() : 0;
      result = result * 37 + (receiver_id != null ? receiver_id.hashCode() : 0);
      result = result * 37 + (transmitter_id != null ? transmitter_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<G4Metadata> {

    public Float receiver_battery_percent;
    public String receiver_id;
    public String transmitter_id;

    public Builder() {
    }

    public Builder(G4Metadata message) {
      super(message);
      if (message == null) return;
      this.receiver_battery_percent = message.receiver_battery_percent;
      this.receiver_id = message.receiver_id;
      this.transmitter_id = message.transmitter_id;
    }

    public Builder receiver_battery_percent(Float receiver_battery_percent) {
      this.receiver_battery_percent = receiver_battery_percent;
      return this;
    }

    /**
     * The receiver id reported by the dexcom g4. This uniquely identifies the device where this Data object came from.
     */
    public Builder receiver_id(String receiver_id) {
      this.receiver_id = receiver_id;
      return this;
    }

    /**
     * The transmitter id reported as used by the dexcom g4. Should look like '6A14AC'.
     */
    public Builder transmitter_id(String transmitter_id) {
      this.transmitter_id = transmitter_id;
      return this;
    }

    @Override
    public G4Metadata build() {
      return new G4Metadata(this);
    }
  }
}
