// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/units.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.ProtoEnum;

public enum GlucoseUnit
    implements ProtoEnum {
  MGDL(0),
  MMOL(1);

  private final int value;

  GlucoseUnit(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
