// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * Next tag: 3
 */
public final class Insertion extends Message {
  private static final long serialVersionUID = 0L;

  public static final State DEFAULT_STATE = State.INSERTION_NONE;

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final State state;

  @ProtoField(tag = 2)
  public final G4Timestamp timestamp;

  public Insertion(State state, G4Timestamp timestamp) {
    this.state = state;
    this.timestamp = timestamp;
  }

  private Insertion(Builder builder) {
    this(builder.state, builder.timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Insertion)) return false;
    Insertion o = (Insertion) other;
    return equals(state, o.state)
        && equals(timestamp, o.timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = state != null ? state.hashCode() : 0;
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Insertion> {

    public State state;
    public G4Timestamp timestamp;

    public Builder() {
    }

    public Builder(Insertion message) {
      super(message);
      if (message == null) return;
      this.state = message.state;
      this.timestamp = message.timestamp;
    }

    public Builder state(State state) {
      this.state = state;
      return this;
    }

    public Builder timestamp(G4Timestamp timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @Override
    public Insertion build() {
      checkRequiredFields();
      return new Insertion(this);
    }
  }

  public enum State
      implements ProtoEnum {
    INSERTION_NONE(0),
    REMOVED(1),
    EXPIRED(2),
    RESIDUAL_DEVIATION(3),
    COUNTS_DEVIATION(4),
    SECOND_SESSION(5),
    OFF_TIME_LOSS(6),
    STARTED(7),
    BAD_TRANSMITTER(8),
    MANUFACTURING_MODE(9),
    MAX_VALUE(10);

    private final int value;

    State(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
