// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * Next tag: 6
 */
public final class RawSensorReading extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_FILTERED = 0L;
  public static final Long DEFAULT_UNFILTERED = 0L;
  public static final Integer DEFAULT_RSSI = 0;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long filtered;

  @ProtoField(tag = 2, type = UINT64)
  public final Long unfiltered;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer rssi;

  @ProtoField(tag = 4)
  public final G4Timestamp timestamp;

  public RawSensorReading(Long filtered, Long unfiltered, Integer rssi, G4Timestamp timestamp) {
    this.filtered = filtered;
    this.unfiltered = unfiltered;
    this.rssi = rssi;
    this.timestamp = timestamp;
  }

  private RawSensorReading(Builder builder) {
    this(builder.filtered, builder.unfiltered, builder.rssi, builder.timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RawSensorReading)) return false;
    RawSensorReading o = (RawSensorReading) other;
    return equals(filtered, o.filtered)
        && equals(unfiltered, o.unfiltered)
        && equals(rssi, o.rssi)
        && equals(timestamp, o.timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = filtered != null ? filtered.hashCode() : 0;
      result = result * 37 + (unfiltered != null ? unfiltered.hashCode() : 0);
      result = result * 37 + (rssi != null ? rssi.hashCode() : 0);
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RawSensorReading> {

    public Long filtered;
    public Long unfiltered;
    public Integer rssi;
    public G4Timestamp timestamp;

    public Builder() {
    }

    public Builder(RawSensorReading message) {
      super(message);
      if (message == null) return;
      this.filtered = message.filtered;
      this.unfiltered = message.unfiltered;
      this.rssi = message.rssi;
      this.timestamp = message.timestamp;
    }

    public Builder filtered(Long filtered) {
      this.filtered = filtered;
      return this;
    }

    public Builder unfiltered(Long unfiltered) {
      this.unfiltered = unfiltered;
      return this;
    }

    public Builder rssi(Integer rssi) {
      this.rssi = rssi;
      return this;
    }

    public Builder timestamp(G4Timestamp timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @Override
    public RawSensorReading build() {
      checkRequiredFields();
      return new RawSensorReading(this);
    }
  }
}
