// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: core/src/main/java/com/nightscout/core/model/v2/g4_data.proto
package com.nightscout.core.model.v2;

import com.squareup.wire.ProtoEnum;

public enum Trend
    implements ProtoEnum {
  TREND_NONE(0),
  /**
   * More than 3 mg/dL per minute
   */
  DOUBLE_UP(1),
  /**
   * +2 to +3 mg/dL per minute
   */
  SINGLE_UP(2),
  /**
   * +1 to +2 mg/dL per minute
   */
  FORTY_FIVE_UP(3),
  /**
   * +/- 1 mg/dL per minute
   */
  FLAT(4),
  /**
   * -1 to -2 mg/dL per minute
   */
  FORTY_FIVE_DOWN(5),
  /**
   * -2 to -3 mg/dL per minute
   */
  SINGLE_DOWN(6),
  /**
   * more than -3 mg/dL per minute
   */
  DOUBLE_DOWN(7),
  NOT_COMPUTABLE(8),
  RATE_OUT_OF_RANGE(9);

  private final int value;

  Trend(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
