// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/SGV.proto

package com.nightscout.android.protobuf;

public final class SGV {
  private SGV() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CookieMonsterG4DownloadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .CookieMonsterSGVG4 sgv = 1;
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> 
        getSgvList();
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 getSgv(int index);
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    int getSgvCount();
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    java.util.List<? extends com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder> 
        getSgvOrBuilderList();
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder getSgvOrBuilder(
        int index);

    // optional .CookieMonsterG4Download.Unit units = 2;
    /**
     * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
     *
     * <pre>
     * Units reported by the device
     * </pre>
     */
    boolean hasUnits();
    /**
     * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
     *
     * <pre>
     * Units reported by the device
     * </pre>
     */
    com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit getUnits();

    // required uint64 download_timestamp = 3;
    /**
     * <code>required uint64 download_timestamp = 3;</code>
     *
     * <pre>
     * Timestamp of the download - should be UTC
     * </pre>
     */
    boolean hasDownloadTimestamp();
    /**
     * <code>required uint64 download_timestamp = 3;</code>
     *
     * <pre>
     * Timestamp of the download - should be UTC
     * </pre>
     */
    long getDownloadTimestamp();

    // optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];
    /**
     * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
     *
     * <pre>
     * Status of the download
     * </pre>
     */
    boolean hasDownloadStatus();
    /**
     * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
     *
     * <pre>
     * Status of the download
     * </pre>
     */
    com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus getDownloadStatus();

    // optional uint32 receiver_battery = 5;
    /**
     * <code>optional uint32 receiver_battery = 5;</code>
     *
     * <pre>
     * Battery level as reported by the receiver
     * </pre>
     */
    boolean hasReceiverBattery();
    /**
     * <code>optional uint32 receiver_battery = 5;</code>
     *
     * <pre>
     * Battery level as reported by the receiver
     * </pre>
     */
    int getReceiverBattery();

    // optional uint32 uploader_battery = 6;
    /**
     * <code>optional uint32 uploader_battery = 6;</code>
     *
     * <pre>
     * Battery level as reported by the uploader
     * </pre>
     */
    boolean hasUploaderBattery();
    /**
     * <code>optional uint32 uploader_battery = 6;</code>
     *
     * <pre>
     * Battery level as reported by the uploader
     * </pre>
     */
    int getUploaderBattery();
  }
  /**
   * Protobuf type {@code CookieMonsterG4Download}
   */
  public static final class CookieMonsterG4Download extends
      com.google.protobuf.GeneratedMessage
      implements CookieMonsterG4DownloadOrBuilder {
    // Use CookieMonsterG4Download.newBuilder() to construct.
    private CookieMonsterG4Download(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CookieMonsterG4Download(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CookieMonsterG4Download defaultInstance;
    public static CookieMonsterG4Download getDefaultInstance() {
      return defaultInstance;
    }

    public CookieMonsterG4Download getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CookieMonsterG4Download(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sgv_ = new java.util.ArrayList<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4>();
                mutable_bitField0_ |= 0x00000001;
              }
              sgv_.add(input.readMessage(com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit value = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                units_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              downloadTimestamp_ = input.readUInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus value = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                downloadStatus_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              receiverBattery_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              uploaderBattery_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sgv_ = java.util.Collections.unmodifiableList(sgv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterG4Download_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterG4Download_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.class, com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Builder.class);
    }

    public static com.google.protobuf.Parser<CookieMonsterG4Download> PARSER =
        new com.google.protobuf.AbstractParser<CookieMonsterG4Download>() {
      public CookieMonsterG4Download parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CookieMonsterG4Download(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CookieMonsterG4Download> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code CookieMonsterG4Download.Unit}
     */
    public enum Unit
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MGDL = 0;</code>
       */
      MGDL(0, 0),
      /**
       * <code>MMOL = 1;</code>
       */
      MMOL(1, 1),
      ;

      /**
       * <code>MGDL = 0;</code>
       */
      public static final int MGDL_VALUE = 0;
      /**
       * <code>MMOL = 1;</code>
       */
      public static final int MMOL_VALUE = 1;


      public final int getNumber() { return value; }

      public static Unit valueOf(int value) {
        switch (value) {
          case 0: return MGDL;
          case 1: return MMOL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Unit>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Unit>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Unit>() {
              public Unit findValueByNumber(int number) {
                return Unit.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.getDescriptor().getEnumTypes().get(0);
      }

      private static final Unit[] VALUES = values();

      public static Unit valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Unit(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CookieMonsterG4Download.Unit)
    }

    /**
     * Protobuf enum {@code CookieMonsterG4Download.DownloadStatus}
     */
    public enum DownloadStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>NO_DATA = 1;</code>
       */
      NO_DATA(1, 1),
      /**
       * <code>DEVICE_NOT_FOUND = 2;</code>
       */
      DEVICE_NOT_FOUND(2, 2),
      /**
       * <code>IO_ERROR = 3;</code>
       */
      IO_ERROR(3, 3),
      /**
       * <code>APPLICATION_ERROR = 4;</code>
       */
      APPLICATION_ERROR(4, 4),
      /**
       * <code>NONE = 6;</code>
       */
      NONE(5, 6),
      /**
       * <code>UNKNOWN = 7;</code>
       */
      UNKNOWN(6, 7),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>NO_DATA = 1;</code>
       */
      public static final int NO_DATA_VALUE = 1;
      /**
       * <code>DEVICE_NOT_FOUND = 2;</code>
       */
      public static final int DEVICE_NOT_FOUND_VALUE = 2;
      /**
       * <code>IO_ERROR = 3;</code>
       */
      public static final int IO_ERROR_VALUE = 3;
      /**
       * <code>APPLICATION_ERROR = 4;</code>
       */
      public static final int APPLICATION_ERROR_VALUE = 4;
      /**
       * <code>NONE = 6;</code>
       */
      public static final int NONE_VALUE = 6;
      /**
       * <code>UNKNOWN = 7;</code>
       */
      public static final int UNKNOWN_VALUE = 7;


      public final int getNumber() { return value; }

      public static DownloadStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return NO_DATA;
          case 2: return DEVICE_NOT_FOUND;
          case 3: return IO_ERROR;
          case 4: return APPLICATION_ERROR;
          case 6: return NONE;
          case 7: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DownloadStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DownloadStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DownloadStatus>() {
              public DownloadStatus findValueByNumber(int number) {
                return DownloadStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.getDescriptor().getEnumTypes().get(1);
      }

      private static final DownloadStatus[] VALUES = values();

      public static DownloadStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DownloadStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CookieMonsterG4Download.DownloadStatus)
    }

    private int bitField0_;
    // repeated .CookieMonsterSGVG4 sgv = 1;
    public static final int SGV_FIELD_NUMBER = 1;
    private java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> sgv_;
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    public java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> getSgvList() {
      return sgv_;
    }
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    public java.util.List<? extends com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder> 
        getSgvOrBuilderList() {
      return sgv_;
    }
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    public int getSgvCount() {
      return sgv_.size();
    }
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 getSgv(int index) {
      return sgv_.get(index);
    }
    /**
     * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
     *
     * <pre>
     * Glucose records as reported by the G4
     * </pre>
     */
    public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder getSgvOrBuilder(
        int index) {
      return sgv_.get(index);
    }

    // optional .CookieMonsterG4Download.Unit units = 2;
    public static final int UNITS_FIELD_NUMBER = 2;
    private com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit units_;
    /**
     * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
     *
     * <pre>
     * Units reported by the device
     * </pre>
     */
    public boolean hasUnits() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
     *
     * <pre>
     * Units reported by the device
     * </pre>
     */
    public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit getUnits() {
      return units_;
    }

    // required uint64 download_timestamp = 3;
    public static final int DOWNLOAD_TIMESTAMP_FIELD_NUMBER = 3;
    private long downloadTimestamp_;
    /**
     * <code>required uint64 download_timestamp = 3;</code>
     *
     * <pre>
     * Timestamp of the download - should be UTC
     * </pre>
     */
    public boolean hasDownloadTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 download_timestamp = 3;</code>
     *
     * <pre>
     * Timestamp of the download - should be UTC
     * </pre>
     */
    public long getDownloadTimestamp() {
      return downloadTimestamp_;
    }

    // optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];
    public static final int DOWNLOAD_STATUS_FIELD_NUMBER = 4;
    private com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus downloadStatus_;
    /**
     * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
     *
     * <pre>
     * Status of the download
     * </pre>
     */
    public boolean hasDownloadStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
     *
     * <pre>
     * Status of the download
     * </pre>
     */
    public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus getDownloadStatus() {
      return downloadStatus_;
    }

    // optional uint32 receiver_battery = 5;
    public static final int RECEIVER_BATTERY_FIELD_NUMBER = 5;
    private int receiverBattery_;
    /**
     * <code>optional uint32 receiver_battery = 5;</code>
     *
     * <pre>
     * Battery level as reported by the receiver
     * </pre>
     */
    public boolean hasReceiverBattery() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 receiver_battery = 5;</code>
     *
     * <pre>
     * Battery level as reported by the receiver
     * </pre>
     */
    public int getReceiverBattery() {
      return receiverBattery_;
    }

    // optional uint32 uploader_battery = 6;
    public static final int UPLOADER_BATTERY_FIELD_NUMBER = 6;
    private int uploaderBattery_;
    /**
     * <code>optional uint32 uploader_battery = 6;</code>
     *
     * <pre>
     * Battery level as reported by the uploader
     * </pre>
     */
    public boolean hasUploaderBattery() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 uploader_battery = 6;</code>
     *
     * <pre>
     * Battery level as reported by the uploader
     * </pre>
     */
    public int getUploaderBattery() {
      return uploaderBattery_;
    }

    private void initFields() {
      sgv_ = java.util.Collections.emptyList();
      units_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit.MGDL;
      downloadTimestamp_ = 0L;
      downloadStatus_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus.NONE;
      receiverBattery_ = 0;
      uploaderBattery_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDownloadTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSgvCount(); i++) {
        if (!getSgv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sgv_.size(); i++) {
        output.writeMessage(1, sgv_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, units_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(3, downloadTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, downloadStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, receiverBattery_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(6, uploaderBattery_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sgv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sgv_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, units_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, downloadTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, downloadStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, receiverBattery_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, uploaderBattery_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nightscout.android.protobuf.SGV.CookieMonsterG4Download prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CookieMonsterG4Download}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nightscout.android.protobuf.SGV.CookieMonsterG4DownloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterG4Download_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterG4Download_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.class, com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Builder.class);
      }

      // Construct using com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSgvFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sgvBuilder_ == null) {
          sgv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sgvBuilder_.clear();
        }
        units_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit.MGDL;
        bitField0_ = (bitField0_ & ~0x00000002);
        downloadTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        downloadStatus_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus.NONE;
        bitField0_ = (bitField0_ & ~0x00000008);
        receiverBattery_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        uploaderBattery_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterG4Download_descriptor;
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download getDefaultInstanceForType() {
        return com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.getDefaultInstance();
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download build() {
        com.nightscout.android.protobuf.SGV.CookieMonsterG4Download result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download buildPartial() {
        com.nightscout.android.protobuf.SGV.CookieMonsterG4Download result = new com.nightscout.android.protobuf.SGV.CookieMonsterG4Download(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (sgvBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sgv_ = java.util.Collections.unmodifiableList(sgv_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sgv_ = sgv_;
        } else {
          result.sgv_ = sgvBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.units_ = units_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.downloadTimestamp_ = downloadTimestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.downloadStatus_ = downloadStatus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.receiverBattery_ = receiverBattery_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uploaderBattery_ = uploaderBattery_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nightscout.android.protobuf.SGV.CookieMonsterG4Download) {
          return mergeFrom((com.nightscout.android.protobuf.SGV.CookieMonsterG4Download)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nightscout.android.protobuf.SGV.CookieMonsterG4Download other) {
        if (other == com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.getDefaultInstance()) return this;
        if (sgvBuilder_ == null) {
          if (!other.sgv_.isEmpty()) {
            if (sgv_.isEmpty()) {
              sgv_ = other.sgv_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSgvIsMutable();
              sgv_.addAll(other.sgv_);
            }
            onChanged();
          }
        } else {
          if (!other.sgv_.isEmpty()) {
            if (sgvBuilder_.isEmpty()) {
              sgvBuilder_.dispose();
              sgvBuilder_ = null;
              sgv_ = other.sgv_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sgvBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSgvFieldBuilder() : null;
            } else {
              sgvBuilder_.addAllMessages(other.sgv_);
            }
          }
        }
        if (other.hasUnits()) {
          setUnits(other.getUnits());
        }
        if (other.hasDownloadTimestamp()) {
          setDownloadTimestamp(other.getDownloadTimestamp());
        }
        if (other.hasDownloadStatus()) {
          setDownloadStatus(other.getDownloadStatus());
        }
        if (other.hasReceiverBattery()) {
          setReceiverBattery(other.getReceiverBattery());
        }
        if (other.hasUploaderBattery()) {
          setUploaderBattery(other.getUploaderBattery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDownloadTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getSgvCount(); i++) {
          if (!getSgv(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nightscout.android.protobuf.SGV.CookieMonsterG4Download parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nightscout.android.protobuf.SGV.CookieMonsterG4Download) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .CookieMonsterSGVG4 sgv = 1;
      private java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> sgv_ =
        java.util.Collections.emptyList();
      private void ensureSgvIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sgv_ = new java.util.ArrayList<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4>(sgv_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder> sgvBuilder_;

      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> getSgvList() {
        if (sgvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sgv_);
        } else {
          return sgvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public int getSgvCount() {
        if (sgvBuilder_ == null) {
          return sgv_.size();
        } else {
          return sgvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 getSgv(int index) {
        if (sgvBuilder_ == null) {
          return sgv_.get(index);
        } else {
          return sgvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder setSgv(
          int index, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 value) {
        if (sgvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSgvIsMutable();
          sgv_.set(index, value);
          onChanged();
        } else {
          sgvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder setSgv(
          int index, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder builderForValue) {
        if (sgvBuilder_ == null) {
          ensureSgvIsMutable();
          sgv_.set(index, builderForValue.build());
          onChanged();
        } else {
          sgvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder addSgv(com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 value) {
        if (sgvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSgvIsMutable();
          sgv_.add(value);
          onChanged();
        } else {
          sgvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder addSgv(
          int index, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 value) {
        if (sgvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSgvIsMutable();
          sgv_.add(index, value);
          onChanged();
        } else {
          sgvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder addSgv(
          com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder builderForValue) {
        if (sgvBuilder_ == null) {
          ensureSgvIsMutable();
          sgv_.add(builderForValue.build());
          onChanged();
        } else {
          sgvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder addSgv(
          int index, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder builderForValue) {
        if (sgvBuilder_ == null) {
          ensureSgvIsMutable();
          sgv_.add(index, builderForValue.build());
          onChanged();
        } else {
          sgvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder addAllSgv(
          java.lang.Iterable<? extends com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4> values) {
        if (sgvBuilder_ == null) {
          ensureSgvIsMutable();
          super.addAll(values, sgv_);
          onChanged();
        } else {
          sgvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder clearSgv() {
        if (sgvBuilder_ == null) {
          sgv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sgvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public Builder removeSgv(int index) {
        if (sgvBuilder_ == null) {
          ensureSgvIsMutable();
          sgv_.remove(index);
          onChanged();
        } else {
          sgvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder getSgvBuilder(
          int index) {
        return getSgvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder getSgvOrBuilder(
          int index) {
        if (sgvBuilder_ == null) {
          return sgv_.get(index);  } else {
          return sgvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public java.util.List<? extends com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder> 
           getSgvOrBuilderList() {
        if (sgvBuilder_ != null) {
          return sgvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sgv_);
        }
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder addSgvBuilder() {
        return getSgvFieldBuilder().addBuilder(
            com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.getDefaultInstance());
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder addSgvBuilder(
          int index) {
        return getSgvFieldBuilder().addBuilder(
            index, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.getDefaultInstance());
      }
      /**
       * <code>repeated .CookieMonsterSGVG4 sgv = 1;</code>
       *
       * <pre>
       * Glucose records as reported by the G4
       * </pre>
       */
      public java.util.List<com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder> 
           getSgvBuilderList() {
        return getSgvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder> 
          getSgvFieldBuilder() {
        if (sgvBuilder_ == null) {
          sgvBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder>(
                  sgv_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sgv_ = null;
        }
        return sgvBuilder_;
      }

      // optional .CookieMonsterG4Download.Unit units = 2;
      private com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit units_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit.MGDL;
      /**
       * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
       *
       * <pre>
       * Units reported by the device
       * </pre>
       */
      public boolean hasUnits() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
       *
       * <pre>
       * Units reported by the device
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit getUnits() {
        return units_;
      }
      /**
       * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
       *
       * <pre>
       * Units reported by the device
       * </pre>
       */
      public Builder setUnits(com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        units_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CookieMonsterG4Download.Unit units = 2;</code>
       *
       * <pre>
       * Units reported by the device
       * </pre>
       */
      public Builder clearUnits() {
        bitField0_ = (bitField0_ & ~0x00000002);
        units_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.Unit.MGDL;
        onChanged();
        return this;
      }

      // required uint64 download_timestamp = 3;
      private long downloadTimestamp_ ;
      /**
       * <code>required uint64 download_timestamp = 3;</code>
       *
       * <pre>
       * Timestamp of the download - should be UTC
       * </pre>
       */
      public boolean hasDownloadTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 download_timestamp = 3;</code>
       *
       * <pre>
       * Timestamp of the download - should be UTC
       * </pre>
       */
      public long getDownloadTimestamp() {
        return downloadTimestamp_;
      }
      /**
       * <code>required uint64 download_timestamp = 3;</code>
       *
       * <pre>
       * Timestamp of the download - should be UTC
       * </pre>
       */
      public Builder setDownloadTimestamp(long value) {
        bitField0_ |= 0x00000004;
        downloadTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 download_timestamp = 3;</code>
       *
       * <pre>
       * Timestamp of the download - should be UTC
       * </pre>
       */
      public Builder clearDownloadTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        downloadTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];
      private com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus downloadStatus_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus.NONE;
      /**
       * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
       *
       * <pre>
       * Status of the download
       * </pre>
       */
      public boolean hasDownloadStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
       *
       * <pre>
       * Status of the download
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus getDownloadStatus() {
        return downloadStatus_;
      }
      /**
       * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
       *
       * <pre>
       * Status of the download
       * </pre>
       */
      public Builder setDownloadStatus(com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        downloadStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CookieMonsterG4Download.DownloadStatus download_status = 4 [default = NONE];</code>
       *
       * <pre>
       * Status of the download
       * </pre>
       */
      public Builder clearDownloadStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        downloadStatus_ = com.nightscout.android.protobuf.SGV.CookieMonsterG4Download.DownloadStatus.NONE;
        onChanged();
        return this;
      }

      // optional uint32 receiver_battery = 5;
      private int receiverBattery_ ;
      /**
       * <code>optional uint32 receiver_battery = 5;</code>
       *
       * <pre>
       * Battery level as reported by the receiver
       * </pre>
       */
      public boolean hasReceiverBattery() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 receiver_battery = 5;</code>
       *
       * <pre>
       * Battery level as reported by the receiver
       * </pre>
       */
      public int getReceiverBattery() {
        return receiverBattery_;
      }
      /**
       * <code>optional uint32 receiver_battery = 5;</code>
       *
       * <pre>
       * Battery level as reported by the receiver
       * </pre>
       */
      public Builder setReceiverBattery(int value) {
        bitField0_ |= 0x00000010;
        receiverBattery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 receiver_battery = 5;</code>
       *
       * <pre>
       * Battery level as reported by the receiver
       * </pre>
       */
      public Builder clearReceiverBattery() {
        bitField0_ = (bitField0_ & ~0x00000010);
        receiverBattery_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 uploader_battery = 6;
      private int uploaderBattery_ ;
      /**
       * <code>optional uint32 uploader_battery = 6;</code>
       *
       * <pre>
       * Battery level as reported by the uploader
       * </pre>
       */
      public boolean hasUploaderBattery() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 uploader_battery = 6;</code>
       *
       * <pre>
       * Battery level as reported by the uploader
       * </pre>
       */
      public int getUploaderBattery() {
        return uploaderBattery_;
      }
      /**
       * <code>optional uint32 uploader_battery = 6;</code>
       *
       * <pre>
       * Battery level as reported by the uploader
       * </pre>
       */
      public Builder setUploaderBattery(int value) {
        bitField0_ |= 0x00000020;
        uploaderBattery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uploader_battery = 6;</code>
       *
       * <pre>
       * Battery level as reported by the uploader
       * </pre>
       */
      public Builder clearUploaderBattery() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uploaderBattery_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CookieMonsterG4Download)
    }

    static {
      defaultInstance = new CookieMonsterG4Download(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CookieMonsterG4Download)
  }

  public interface CookieMonsterSGVG4OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 sgv = 1;
    /**
     * <code>required uint32 sgv = 1;</code>
     *
     * <pre>
     * Glucose value
     * </pre>
     */
    boolean hasSgv();
    /**
     * <code>required uint32 sgv = 1;</code>
     *
     * <pre>
     * Glucose value
     * </pre>
     */
    int getSgv();

    // optional uint64 timestamp = 2;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * timestamp of the record
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * timestamp of the record
     * </pre>
     */
    long getTimestamp();

    // optional .CookieMonsterSGVG4.Direction direction = 3;
    /**
     * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
     *
     * <pre>
     * Trend arrow
     * </pre>
     */
    boolean hasDirection();
    /**
     * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
     *
     * <pre>
     * Trend arrow
     * </pre>
     */
    com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction getDirection();
  }
  /**
   * Protobuf type {@code CookieMonsterSGVG4}
   */
  public static final class CookieMonsterSGVG4 extends
      com.google.protobuf.GeneratedMessage
      implements CookieMonsterSGVG4OrBuilder {
    // Use CookieMonsterSGVG4.newBuilder() to construct.
    private CookieMonsterSGVG4(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CookieMonsterSGVG4(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CookieMonsterSGVG4 defaultInstance;
    public static CookieMonsterSGVG4 getDefaultInstance() {
      return defaultInstance;
    }

    public CookieMonsterSGVG4 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CookieMonsterSGVG4(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sgv_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction value = com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                direction_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterSGVG4_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterSGVG4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.class, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder.class);
    }

    public static com.google.protobuf.Parser<CookieMonsterSGVG4> PARSER =
        new com.google.protobuf.AbstractParser<CookieMonsterSGVG4>() {
      public CookieMonsterSGVG4 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CookieMonsterSGVG4(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CookieMonsterSGVG4> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code CookieMonsterSGVG4.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0, 0),
      /**
       * <code>DOUBLE_UP = 1;</code>
       */
      DOUBLE_UP(1, 1),
      /**
       * <code>SINGLE_UP = 2;</code>
       */
      SINGLE_UP(2, 2),
      /**
       * <code>FORTY_FIVE_UP = 3;</code>
       */
      FORTY_FIVE_UP(3, 3),
      /**
       * <code>FLAT = 4;</code>
       */
      FLAT(4, 4),
      /**
       * <code>FORTY_FIVE_DOWN = 5;</code>
       */
      FORTY_FIVE_DOWN(5, 5),
      /**
       * <code>SINGLE_DOWN = 6;</code>
       */
      SINGLE_DOWN(6, 6),
      /**
       * <code>DOUBLE_DOWN = 7;</code>
       */
      DOUBLE_DOWN(7, 7),
      /**
       * <code>NOT_COMPUTABLE = 8;</code>
       */
      NOT_COMPUTABLE(8, 8),
      /**
       * <code>RATE_OUT_OF_RANGE = 9;</code>
       */
      RATE_OUT_OF_RANGE(9, 9),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>DOUBLE_UP = 1;</code>
       */
      public static final int DOUBLE_UP_VALUE = 1;
      /**
       * <code>SINGLE_UP = 2;</code>
       */
      public static final int SINGLE_UP_VALUE = 2;
      /**
       * <code>FORTY_FIVE_UP = 3;</code>
       */
      public static final int FORTY_FIVE_UP_VALUE = 3;
      /**
       * <code>FLAT = 4;</code>
       */
      public static final int FLAT_VALUE = 4;
      /**
       * <code>FORTY_FIVE_DOWN = 5;</code>
       */
      public static final int FORTY_FIVE_DOWN_VALUE = 5;
      /**
       * <code>SINGLE_DOWN = 6;</code>
       */
      public static final int SINGLE_DOWN_VALUE = 6;
      /**
       * <code>DOUBLE_DOWN = 7;</code>
       */
      public static final int DOUBLE_DOWN_VALUE = 7;
      /**
       * <code>NOT_COMPUTABLE = 8;</code>
       */
      public static final int NOT_COMPUTABLE_VALUE = 8;
      /**
       * <code>RATE_OUT_OF_RANGE = 9;</code>
       */
      public static final int RATE_OUT_OF_RANGE_VALUE = 9;


      public final int getNumber() { return value; }

      public static Direction valueOf(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return DOUBLE_UP;
          case 2: return SINGLE_UP;
          case 3: return FORTY_FIVE_UP;
          case 4: return FLAT;
          case 5: return FORTY_FIVE_DOWN;
          case 6: return SINGLE_DOWN;
          case 7: return DOUBLE_DOWN;
          case 8: return NOT_COMPUTABLE;
          case 9: return RATE_OUT_OF_RANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CookieMonsterSGVG4.Direction)
    }

    private int bitField0_;
    // required uint32 sgv = 1;
    public static final int SGV_FIELD_NUMBER = 1;
    private int sgv_;
    /**
     * <code>required uint32 sgv = 1;</code>
     *
     * <pre>
     * Glucose value
     * </pre>
     */
    public boolean hasSgv() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 sgv = 1;</code>
     *
     * <pre>
     * Glucose value
     * </pre>
     */
    public int getSgv() {
      return sgv_;
    }

    // optional uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * timestamp of the record
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * timestamp of the record
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional .CookieMonsterSGVG4.Direction direction = 3;
    public static final int DIRECTION_FIELD_NUMBER = 3;
    private com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction direction_;
    /**
     * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
     *
     * <pre>
     * Trend arrow
     * </pre>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
     *
     * <pre>
     * Trend arrow
     * </pre>
     */
    public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction getDirection() {
      return direction_;
    }

    private void initFields() {
      sgv_ = 0;
      timestamp_ = 0L;
      direction_ = com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction.NONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSgv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, sgv_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, direction_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, sgv_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, direction_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CookieMonsterSGVG4}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterSGVG4_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterSGVG4_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.class, com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Builder.class);
      }

      // Construct using com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sgv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        direction_ = com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction.NONE;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nightscout.android.protobuf.SGV.internal_static_CookieMonsterSGVG4_descriptor;
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 getDefaultInstanceForType() {
        return com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.getDefaultInstance();
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 build() {
        com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 buildPartial() {
        com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 result = new com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sgv_ = sgv_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.direction_ = direction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4) {
          return mergeFrom((com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 other) {
        if (other == com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.getDefaultInstance()) return this;
        if (other.hasSgv()) {
          setSgv(other.getSgv());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSgv()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 sgv = 1;
      private int sgv_ ;
      /**
       * <code>required uint32 sgv = 1;</code>
       *
       * <pre>
       * Glucose value
       * </pre>
       */
      public boolean hasSgv() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 sgv = 1;</code>
       *
       * <pre>
       * Glucose value
       * </pre>
       */
      public int getSgv() {
        return sgv_;
      }
      /**
       * <code>required uint32 sgv = 1;</code>
       *
       * <pre>
       * Glucose value
       * </pre>
       */
      public Builder setSgv(int value) {
        bitField0_ |= 0x00000001;
        sgv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 sgv = 1;</code>
       *
       * <pre>
       * Glucose value
       * </pre>
       */
      public Builder clearSgv() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sgv_ = 0;
        onChanged();
        return this;
      }

      // optional uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * timestamp of the record
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * timestamp of the record
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * timestamp of the record
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * timestamp of the record
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .CookieMonsterSGVG4.Direction direction = 3;
      private com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction direction_ = com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction.NONE;
      /**
       * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
       *
       * <pre>
       * Trend arrow
       * </pre>
       */
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
       *
       * <pre>
       * Trend arrow
       * </pre>
       */
      public com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction getDirection() {
        return direction_;
      }
      /**
       * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
       *
       * <pre>
       * Trend arrow
       * </pre>
       */
      public Builder setDirection(com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CookieMonsterSGVG4.Direction direction = 3;</code>
       *
       * <pre>
       * Trend arrow
       * </pre>
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        direction_ = com.nightscout.android.protobuf.SGV.CookieMonsterSGVG4.Direction.NONE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CookieMonsterSGVG4)
    }

    static {
      defaultInstance = new CookieMonsterSGVG4(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CookieMonsterSGVG4)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CookieMonsterG4Download_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CookieMonsterG4Download_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CookieMonsterSGVG4_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CookieMonsterSGVG4_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protobuf/SGV.proto\"\233\003\n\027CookieMonsterG4" +
      "Download\022 \n\003sgv\030\001 \003(\0132\023.CookieMonsterSGV" +
      "G4\022,\n\005units\030\002 \001(\0162\035.CookieMonsterG4Downl" +
      "oad.Unit\022\032\n\022download_timestamp\030\003 \002(\004\022F\n\017" +
      "download_status\030\004 \001(\0162\'.CookieMonsterG4D" +
      "ownload.DownloadStatus:\004NONE\022\030\n\020receiver" +
      "_battery\030\005 \001(\r\022\030\n\020uploader_battery\030\006 \001(\r" +
      "\"\032\n\004Unit\022\010\n\004MGDL\020\000\022\010\n\004MMOL\020\001\"|\n\016Download" +
      "Status\022\013\n\007SUCCESS\020\000\022\013\n\007NO_DATA\020\001\022\024\n\020DEVI" +
      "CE_NOT_FOUND\020\002\022\014\n\010IO_ERROR\020\003\022\025\n\021APPLICAT",
      "ION_ERROR\020\004\022\010\n\004NONE\020\006\022\013\n\007UNKNOWN\020\007\"\233\002\n\022C" +
      "ookieMonsterSGVG4\022\013\n\003sgv\030\001 \002(\r\022\021\n\ttimest" +
      "amp\030\002 \001(\004\0220\n\tdirection\030\003 \001(\0162\035.CookieMon" +
      "sterSGVG4.Direction\"\262\001\n\tDirection\022\010\n\004NON" +
      "E\020\000\022\r\n\tDOUBLE_UP\020\001\022\r\n\tSINGLE_UP\020\002\022\021\n\rFOR" +
      "TY_FIVE_UP\020\003\022\010\n\004FLAT\020\004\022\023\n\017FORTY_FIVE_DOW" +
      "N\020\005\022\017\n\013SINGLE_DOWN\020\006\022\017\n\013DOUBLE_DOWN\020\007\022\022\n" +
      "\016NOT_COMPUTABLE\020\010\022\025\n\021RATE_OUT_OF_RANGE\020\t" +
      "B&\n\037com.nightscout.android.protobufB\003SGV"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CookieMonsterG4Download_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CookieMonsterG4Download_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CookieMonsterG4Download_descriptor,
              new java.lang.String[] { "Sgv", "Units", "DownloadTimestamp", "DownloadStatus", "ReceiverBattery", "UploaderBattery", });
          internal_static_CookieMonsterSGVG4_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CookieMonsterSGVG4_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CookieMonsterSGVG4_descriptor,
              new java.lang.String[] { "Sgv", "Timestamp", "Direction", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
