package com.nightscout.core.drivers.Medtronic;

public enum RecordType {
    BATTERY_ACTIVITY,
    PUMP_SUSPENDED,
    PUMP_RESUMED,
    REWOUND,
    TOGGLE_REMOTE,
    CHANGE_REMOTE_ID,
    TEMP_BASAL_DURATION,
    TEMP_BASAL_RATE,
    LOW_RESERVOIR,
    CHANGE_UTILITY,
    CHANGE_TIME_DISPLAY,
    BASAL_PROFILE_START,
    BOLUS_WIZARD_CHANGE,
    OLD_6C,
    RESULT_TOTALS,
    MIDNIGHT_TOTALS,
    NO_DELIVERY_ALARM,
    END_RESULTS_TOTALS, // Is this right?
    CHANGE_BASAL_PROFILE,
    CLEAR_ALARM,
    SELECT_BASAL_PROFILE,
    CHANGE_TIME,
    NEW_TIME_SET,
    LOW_BATTERY,
    BOLUS,
    BOLUS_WIZARD,
    UNABSORBED_INSULIN,
    PRIME,
    CAL_BG_FOR_PH;
}
