package com.nightscout.android.analyzers;

public enum Condition {
    CRITICALHIGH,
    WARNHIGH,
    INRANGE,
    WARNLOW,
    CRITICALLOW,
    DOWNLOADFAILED,
    DEVICEDISCONNECTED,
    NODATA,
    STALEDATA,
    UPLOADERCRITICALLOW,
    UPLOADERLOW,
    DEVICECRITICALLOW,
    DEVICELOW,
    DEVICEMSGS,
    UNKNOWN,
    NONE,
    REMOTEDISCONNECTED,
    MISSEDREADING,
    SPECIALVALUE,
    READINGTIME,
    MONGONOTCONNECTED
}